# Generated by Django 4.1.1 on 2022-09-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='total_ratio',
        ),
        migrations.RemoveField(
            model_name='review',
            name='total_vote',
        ),
        migrations.AddField(
            model_name='project',
            name='total_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_vote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
