# Generated by Django 4.1.1 on 2022-09-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_review_total_ratio_remove_review_total_vote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_ratio',
            new_name='vote_ratio',
        ),
    ]
